version: "3.9"

services:
  mysql:
    container_name: spring-scheduler-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spring-scheduler
      MYSQL_ROOT_PASSWORD: root

